' Developer Express Code Central Example:
' How to merge cells horizontally in GridView via the CustomDrawCell event
' 
' This example illustrates an approach that is similar to that one described in
' the following thread: http://www.devexpress.com/scid=E2472.
' The mentioned
' functionality is implemented via the GridView.CustomDrawCell event handling.
' In
' addition, this example illustrates how to implement merged text scrolling.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E4039

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace My


	<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")>
	Friend NotInheritable Partial Class Settings
		Inherits System.Configuration.ApplicationSettingsBase

		Private Shared defaultInstance As Settings = (CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings))

		Public Shared ReadOnly Property [Default]() As Settings
			Get
				Return defaultInstance
			End Get
		End Property
	End Class
End Namespace
